apps/blog/urls.py
from django.urls import path

from apps.blog.views import AboutView, HomeView
from apps.blog.views.posts import PostDetailView, PostListView
from apps.blog.views.projects import ProjectsTemplateView
from apps.blog.views.resume import ResumeDownloadView, ResumePreviewView, ResumeView

app_name = "blog"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("posts/", PostListView.as_view(), name="posts"),
    path("posts/<slug:slug>/", PostDetailView.as_view(), name="post_detail"),
    path("projects/", ProjectsTemplateView.as_view(), name="projects"),
    path("resume/", ResumeView.as_view(), name="resume"),
    path("resume/preview/", ResumePreviewView.as_view(), name="resume_preview"),
    path("resume/download/", ResumeDownloadView.as_view(), name="resume_download"),
]

config/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path

from apps.blog.views import serve_seaweedfs_file, tinymce_upload_image

urlpatterns = [
    # Apps URLs
    path("", include(("apps.blog.urls", "blog"), namespace="blog")),
    # Admin URLs
    path("admin/tinymce-upload/", tinymce_upload_image, name="tinymce-upload"),
    path("admin/", admin.site.urls),
    # Third-party URLs
    path("tinymce/", include("tinymce.urls")),
]

if not settings.DEBUG:
    urlpatterns += [
        path("", include("django_prometheus.urls")),
    ]

if settings.DEBUG:
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
        re_path(
            r"^trungstacks-blog-media/(?P<path>.*)$",
            serve_seaweedfs_file,
            name="seaweedfs-serve",
        ),
        *debug_toolbar_urls(),
    ]

templates/base.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en" class="group/darkmode h-full">
	<head>
		<title>{% block title %}Trung Dev{% endblock title %}</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		<link rel="icon" type="image/png" href="{% static 'icons/favicon.ico' %}">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
		{% tailwind_css %}
		{% block prismcss %}{% endblock prismcss %}

		{% block extrahead %}
			<meta name="description" content="Personal website written in Django by Trung" />
		{% endblock extrahead %}
	</head>

	<body class="h-full">
		<section id="root" class="h-full">
			{% include "header.html" %}
			{% include "sidebar.html" %}
			<div id="main-content" class="pt-[var(--header-height)] ml-0 md:[&.open]:ml-[var(--sidebar-width)] transition-[margin-left] duration-300 ease-in-out flex flex-col min-h-full items-center">
				<script src="{% static 'js/nav-bar.js' %}"></script>

				<div class="flex-grow w-full lg:max-w-4xl 2xl:max-w-5xl">{% block content %}<div>No content available</div>{% endblock content %}</div>
				
				{% include "footer.html" %}
			</div>
		</section>

		{% block prismjs %}{% endblock prismjs %}
	</body>
</html>

templates/footer.html
{% load static %}

<footer class="p-6 shadow-lg border-t-2 border-t-border-muted w-full">
    <div class="flex flex-col items-center justify-center gap-2">
        {% comment %} <span class="text-center">
            Huge thanks to
            <a
                href="https://tania.dev"
                target="_blank"
                class="text-blue-500 hover:underline"
                rel="noopener noreferrer"
            >
                Tania
            </a>
            — her work was a big inspiration for this project
        </span> {% endcomment %}
        <span>
            Made by Trung
            <img
                class="inline-block h-6 w-6"
                src="{% static 'icons/heart.png' %}"
                alt="Made with love"
            />
        </span>
    </div>
</footer>

templates/header.html
{% load static %}
{% load active_link_tags %}

<header class="fixed left-0 top-0 z-50 h-[var(--header-height)] w-full shadow-lg border-b border-b-border-muted backdrop-blur-sm">
    <div class="flex h-full w-full justify-between">
        <div class="flex w-[var(--sidebar-width)] border-r-border-muted items-center justify-between border-r px-4">
            <a class="flex items-end gap-2" href="{% url 'blog:home' %}">
                <img class="h-6 w-6" src="{% static 'icons/logo.svg' %}" alt="logo">
                <span class="hover:underline decoration-2 font-bold">trng.dev</span>
            </a>

            <button id="toggle-sidebar-desktop" style="display: none;" class="hidden md:block group/nav hover:bg-background-navbar-link-hover hover:text-gold px-3 py-2 rounded-lg" onclick="toggleNav.bind(this)()">
                <svg class="hidden group-[.open]/nav:block" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M4 4m0 2a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2z"></path><path d="M9 4v16"></path><path d="M15 10l-2 2l2 2"></path></svg>

                <svg class="block group-[.open]/nav:hidden" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M4 4m0 2a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2z"></path><path d="M9 4v16"></path><path d="M14 10l2 2l-2 2"></path></svg>
            </button>

            <button
                id="toggle-sidebar-mobile"
                class="md:hidden shadow-sm relative w-10 h-10 flex flex-col items-center justify-center group [&.open]:border-2 rounded-md [&.open]:border-gold [&.open]:bg-background-navbar-link-hover transition-all"
                onclick="toggleNav.bind(this)()"
            >
                <!-- Top bar -->
                <span class="block w-6 h-0.5 transition-transform duration-300 ease-in-out group-[.open]:rotate-45 group-[.open]:translate-y-1.5 bg-primary group-[.open]:bg-gold"></span>
                
                <!-- Middle bar -->
                <span class="block w-6 h-0.5 my-1 transition-opacity duration-300 ease-in-out group-[.open]:opacity-0 bg-primary"></span>
                
                <!-- Bottom bar -->
                <span class="block w-6 h-0.5 transition-transform duration-300 ease-in-out group-[.open]:-rotate-45 group-[.open]:-translate-y-1.5 bg-primary group-[.open]:bg-gold"></span>
            </button>
        </div>

        <section class="flex gap-4 mr-4">
            <nav class="md:block hidden">
                <ul class="flex gap-4 items-center h-full header-actions">
                    <li>
                        <a href="{% url 'blog:posts' %}" class="btn-nav {% active_link 'blog:posts || blog:post_detail' strict=True %}">
                            <img src="{% static 'icons/posts.svg' %}" alt="posts">
                            Posts
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'blog:projects' %}" class="btn-nav {% active_link 'blog:projects' strict=True %}">
                            <img class="fill-gold" src="{% static 'icons/projects.svg' %}" alt="projects">
                            Projects
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'blog:about' %}" class="btn-nav {% active_link 'blog:about' strict=True %}">
                            <img src="{% static 'icons/face.svg' %}" alt="about-me">
                            About
                        </a>
                    </li>
                </ul>
            </nav>

            <ul class="flex items-center gap-2 md:gap-4 social-actions">
                <li>
                    <button id="toggle-darkmode" class="group/darkmode" onclick="toggleDarkMode()">
                        <img class="hidden group-[.dark]/darkmode:block h-6 w-6" src="{% static 'icons/moon.svg' %}" alt="darkmode">
                        <img class="block group-[.dark]/darkmode:hidden h-6 w-6" src="{% static 'icons/sun.svg' %}" alt="darkmode">
                    </button>
                </li>
                <li><a class="block fill-primary" href="{{ github_link|default:"#" }}" target="_blank" rel="noopener noreferrer"><svg class="" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" width="24" height="24" x="0" y="0" viewBox="0 0 24 24" style="enable-background:new 0 0 512 512" xml:space="preserve" class=""><g><path d="M12 .5C5.37.5 0 5.78 0 12.292c0 5.211 3.438 9.63 8.205 11.188.6.111.82-.254.82-.567 0-.28-.01-1.022-.015-2.005-3.338.711-4.042-1.582-4.042-1.582-.546-1.361-1.335-1.725-1.335-1.725-1.087-.731.084-.716.084-.716 1.205.082 1.838 1.215 1.838 1.215 1.07 1.803 2.809 1.282 3.495.981.108-.763.417-1.282.76-1.577-2.665-.295-5.466-1.309-5.466-5.827 0-1.287.465-2.339 1.235-3.164-.135-.298-.54-1.497.105-3.121 0 0 1.005-.316 3.3 1.209.96-.262 1.98-.392 3-.398 1.02.006 2.04.136 3 .398 2.28-1.525 3.285-1.209 3.285-1.209.645 1.624.24 2.823.12 3.121.765.825 1.23 1.877 1.23 3.164 0 4.53-2.805 5.527-5.475 5.817.42.354.81 1.077.81 2.182 0 1.578-.015 2.846-.015 3.229 0 .309.21.678.825.56C20.565 21.917 24 17.495 24 12.292 24 5.78 18.627.5 12 .5z" fill="currentColor" opacity="1" data-original="#000000"></path></g></svg></a></li>
                <li><a class="h-6 w-6 block" href="{{ linkedin_link|default:"#"}}" target="_blank" rel="noopener noreferrer"><img src="{% static 'icons/linkedin.png' %}" alt=""></a></li>
            </ul>
        </section>
    </div>
</header>

templates/sidebar.html
{% load static %}
{% load active_link_tags %}

<aside id="nav-sidebar" class="fixed top-0 -left-full [&.open]:left-0 h-full w-full md:w-[var(--sidebar-width)] bg-background-primary mt-[var(--header-height)] shadow-lg z-40 border-r border-r-border-muted transition-[left] duration-300 ease-in-out">
    <nav class="h-full flex gap-4 justify-center items-center pb-[40vh]">
        <ul class="space-y-4 header-actions">
            <li>
                <a href="{% url 'blog:posts' %}" class="btn-nav {% active_link 'blog:posts || blog:post_detail' strict=True %}">
                    <img src="{% static 'icons/posts.svg' %}" alt="posts">
                    Posts
                </a>
            </li>
            <li>
                <a href="{% url 'blog:projects' %}" class="btn-nav {% active_link 'blog:projects' strict=True %}">
                    <img class="fill-gold" src="{% static 'icons/projects.svg' %}" alt="projects">
                    Projects
                </a>
            </li>
            <li>
                <a href="{% url 'blog:about' %}" class="btn-nav {% active_link 'blog:about' strict=True %}">
                    <img src="{% static 'icons/face.svg' %}" alt="about-me">
                    About
                </a>
            </li>
        </ul>
    </nav>
</aside>